version: "3"
services:
    elasticsearch:
        build: ./app/elasticsearch
        container_name: elasticsearch63
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - /data/var/etc/elasticsearch/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml
            - /data/var/etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - /data/var/lib/elasticsearch:/usr/share/elasticsearch/data
        networks:
            - elk-network
        restart: always
    kibana:
        images: docker.elastic.co/kibana/kibana:6.3.0
        container_name: kibana63
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"
        volumes:
            - /data/var/etc/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        environment:
            ELASTICSEARCH_URL: http://172.17.0.1:9200
        networks:
            - elk-network
        restart: always
    logstash:
        images: docker.elastic.co/logstash/logstash:6.3.0
        container_name: logstash63
        depends_on:
            - elasticsearch
        networks:
            - elk-network
        restart: always
    filebeat:
        images: docker.elastic.co/beats/filebeat:6.3.0
        container_name: filebeat63
        depends_on:
            - elasticsearch
        volumes:   
            - /data/var/etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - /data/var/etc/filebeat/prospectors.d:/usr/share/filebeat/prospectors.d
        networks:
            - elk-network
        restart: always
networks:
    elk-network:
        driver: bridge
